# Generated by Django 3.2.12 on 2024-03-23 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polluser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='polluser',
            name='password',
        ),
    ]
