# Generated by Django 3.2.12 on 2024-03-26 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20240323_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='polluser',
            name='city',
            field=models.CharField(default='Defualt City', max_length=100),
        ),
        migrations.AddField(
            model_name='polluser',
            name='country',
            field=models.CharField(default='Defualt Country', max_length=100),
        ),
        migrations.AddField(
            model_name='polluser',
            name='username',
            field=models.CharField(default='Defualt Username', max_length=100),
        ),
    ]
