# Generated by Django 3.2.12 on 2024-03-26 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20240326_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polluser',
            name='username',
            field=models.CharField(default='Default Username', max_length=100),
        ),
    ]
