# Generated by Django 3.2.12 on 2024-03-26 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_polluser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polluser',
            name='city',
        ),
        migrations.RemoveField(
            model_name='polluser',
            name='country',
        ),
        migrations.RemoveField(
            model_name='polluser',
            name='username',
        ),
    ]
