# Generated by Django 3.2.12 on 2024-03-30 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_userimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userimage',
            old_name='image',
            new_name='user_image',
        ),
    ]
