# Generated by Django 3.2.12 on 2024-03-31 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_usercount_last_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('admins', models.ManyToManyField(related_name='admin_of_groups', to='polls.PollUser')),
                ('members', models.ManyToManyField(related_name='groups', to='polls.PollUser')),
            ],
        ),
    ]
