# Generated by Django 3.2.12 on 2024-04-03 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_auto_20240403_1432'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCount',
        ),
    ]
