# Generated by Django 3.2.12 on 2024-04-04 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_polluser_preferences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polluser',
            name='preferences',
        ),
    ]
