# Generated by Django 3.2.12 on 2024-04-04 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AlterField(
            model_name='userimage',
            name='user_image',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
