# Generated by Django 3.2.12 on 2024-04-05 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_auto_20240404_1954'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserImage',
        ),
    ]
