# Generated by Django 3.2.12 on 2024-04-06 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_delete_userimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='polluser',
            name='subscription',
            field=models.CharField(default='default_subscription', max_length=40),
        ),
    ]
